# SPDX-FileCopyrightText: 2026 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

"""Per-request ``llm.request`` rows recovered from a finished Claude CLI stream-json log.

The CLI emits one ``assistant`` row per content block, all sharing the model request's ``message.id``; each carries
that request's prompt-side usage, but its ``output_tokens`` is a streaming snapshot. When the per-request outputs do
not add up to the ``result`` row's total, the rows say so (``output_tokens_exact=False``) instead of guessing a split.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .parse_usage import _claude_result_output_tokens, _claude_stream_model, _iter_json_events, normalize_usage
from .tool_events import TIMING_NONE
from .trajectory_trace import EVENT_LLM_REQUEST, STATUS_COMPLETED, record_event


def stream_json_requests(log_path: str | Path) -> list[dict[str, Any]]:
    """One dict per distinct model request of a stream-json log, in first-seen order."""
    requests: dict[str, dict[str, Any]] = {}
    session_output: int | None = None
    init_model: str | None = None
    for obj in _iter_json_events(log_path, "stream-json"):
        if obj.get("type") == "system":
            init_model = _claude_stream_model(obj) or init_model
            continue
        if obj.get("type") == "result":
            session_output = _claude_result_output_tokens(obj)
            continue
        if obj.get("type") != "assistant":
            continue
        message = obj.get("message")
        if not isinstance(message, dict):
            continue
        message_id = message.get("id")
        raw_model = message.get("model")
        # ``<synthetic>`` messages are generated by the CLI itself and never reached a gateway.
        if not isinstance(message_id, str) or not message_id or str(raw_model or "").startswith("<"):
            continue
        model = _claude_stream_model(obj) or init_model
        request = requests.setdefault(
            message_id,
            {"message_id": message_id, "model": model, "parent_tool_use_id": obj.get("parent_tool_use_id")},
        )
        usage = normalize_usage(message.get("usage") if isinstance(message.get("usage"), dict) else None)
        if usage is not None:
            request.update({key: value for key, value in usage.items() if value is not None})
        stop_reason = message.get("stop_reason")
        if isinstance(stop_reason, str) and stop_reason:
            request["stop_reason"] = stop_reason
    rows = list(requests.values())
    observed = sum(int(row.get("output_tokens") or 0) for row in rows)
    exact = session_output is not None and observed == session_output
    for index, row in enumerate(rows):
        row["request_index"] = index
        row["output_tokens_exact"] = exact
    return rows


def record_stream_json_requests(log_path: str | Path) -> int:
    """Put every model request of a finished stream-json log on the trajectory; returns how many rows were written.

    The log has no per-line timestamps, so these rows are untimed (``timing_source="none"``).
    """
    written = 0
    for request in stream_json_requests(log_path):
        span_id = record_event(
            EVENT_LLM_REQUEST,
            status=STATUS_COMPLETED,
            attributes={**request, "name": request["model"] or "llm", "timing_source": TIMING_NONE, "complete": True},
        )
        written += span_id is not None
    return written


__all__ = ["record_stream_json_requests", "stream_json_requests"]
